// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAheUPGSaYivlQmfc8nbb-2ytvV2mfKLfg',
    appId: '1:1008503113654:web:78b732a8d36700f182a317',
    messagingSenderId: '1008503113654',
    projectId: 'smart-darzi-web',
    authDomain: 'smart-darzi-web.firebaseapp.com',
    storageBucket: 'smart-darzi-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGXW5j4THeSF8u0TwaiemzB7HDZZtj1XA',
    appId: '1:1008503113654:android:1bd74c4f8c4d9d5682a317',
    messagingSenderId: '1008503113654',
    projectId: 'smart-darzi-web',
    storageBucket: 'smart-darzi-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyZ_TEXIzu5p66tShXC7nkHoAv_JTLwAM',
    appId: '1:1008503113654:ios:ddcfd17680911a2382a317',
    messagingSenderId: '1008503113654',
    projectId: 'smart-darzi-web',
    storageBucket: 'smart-darzi-web.appspot.com',
    iosBundleId: 'com.example.smartDarzi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyZ_TEXIzu5p66tShXC7nkHoAv_JTLwAM',
    appId: '1:1008503113654:ios:431a6430406b8d6382a317',
    messagingSenderId: '1008503113654',
    projectId: 'smart-darzi-web',
    storageBucket: 'smart-darzi-web.appspot.com',
    iosBundleId: 'com.example.smartDarzi.RunnerTests',
  );
}
